[workspace]
members = [
    "core",
    "driver",
    "e2e",
    "price-estimator",
    "pricegraph",
    "pricegraph/fuzz",
    "pricegraph/wasm",
]
default-members = [
    "core",
    "driver",
    "price-estimator",
    "pricegraph",
]

[profile.release]
opt-level = "s"

[patch.crates-io]
# Needed to make coverage work on MacOS (https://github.com/servo/core-foundation-rs/pull/357)
core-foundation = { git = "https://github.com/servo/core-foundation-rs", tag="v0.20.1"}
core-foundation-sys = { git = "https://github.com/servo/core-foundation-rs", tag="v0.20.1"}

