[workspace]
members = [
    "driver",
    "e2e",
    "pricegraph",
    "pricegraph/wasm",
    "pricegraph/fuzz",
]
default-members = [
    "driver",
    "pricegraph",
]

[profile.release]
opt-level = "s"
