[workspace]
members = [
    "dfusion_rust_core",
    "driver",
    "listener",
    "e2e",
]
default-members = [
    "dfusion_rust_core",
    "driver",
    "listener",
]

[patch.crates-io]
web3 = { git = "https://github.com/graphprotocol/rust-web3", branch = "graph-patches" }
