version: "3.6"
services:
  stablex:
    command: ./driver
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
      args:
        - RUST_BASE=rust-binary
    image: stablex-binary
    volumes: [] # don't mount volumes as name clashes with name of the binary
    environment:
      - RUST_BACKTRACE=1
