version: "3.6"
services:
  stablex:
    build:
      context: .
      dockerfile: docker/rust/stablex_binary/Dockerfile
    image: stablex-binary
    command: ./stablex
  driver:
    build:
      context: .
      dockerfile: docker/rust/stablex_binary/Dockerfile
    image: stablex-binary
    command: ./dfusion
  graph-listener:
    build:
      context: .
      dockerfile: docker/rust/stablex_binary/Dockerfile
    image: stablex-binary
    command: ./graph-listener
