version: "3.6"
services:
  stablex:
    command: ./driver
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
      args:
        - RUST_BASE=rust-binary
    image: stablex-binary
    environment:
      - RUST_BACKTRACE=1
