#!/bin/sh
set -e

CHANGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")
CHANGED_RS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".rs$")


if [[ ("CHANGED_RS_FILES" != "") ]]; then
    echo 'Running cargo test'
    cd driver
    cargo test
    cd ..
else
    echo 'Skipping cargo test; Branch does not differ from master in a rusty way!'
fi

if [[ ("CHANGED_PY_FILES" != "") ]]; then
    echo 'Running pytest'
    pytest event_listener/dfusion_db
else
    echo 'Skipping pytest; Branch does not differ from master in a pythonic way!'
fi
